# Start AeroSpace at login
start-at-login = false

after-startup-command = [
  'exec-and-forget borders active_color=0xff188bc2 inactive_color=0xff494d64 width=10.0'
]

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 80

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodness#disable-hide-app
automatically-unhide-macos-hidden-apps = true

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       5
outer.bottom =     5
outer.top =        5
outer.right =      5

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]

cmd-h = [] # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
alt-ctrl-shift-comma = '''exec-and-forget osascript -e '
tell application "Firefox"
    open location "https://ballard.amazon.com/owa/#path=/calendar/view/WorkWeek"
end tell'
'''
alt-ctrl-shift-period = '''exec-and-forget osascript -e '
tell application "Firefox"
    open location "https://ballard.amazon.com/owa/#path=/mail"
end tell'
'''

alt-ctrl-shift-cmd-f = 'fullscreen'
alt-ctrl-shift-f = 'layout h_accordion h_tiles'
alt-ctrl-shift-b = 'balance-sizes'


# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-ctrl-shift-a = 'focus left --boundaries workspace --boundaries-action wrap-around-the-workspace'
alt-ctrl-shift-s = 'focus down --boundaries workspace --boundaries-action wrap-around-the-workspace'
alt-ctrl-shift-w = 'focus up --boundaries workspace --boundaries-action wrap-around-the-workspace'
alt-ctrl-shift-d = 'focus right --boundaries workspace --boundaries-action wrap-around-the-workspace'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-ctrl-shift-cmd-a = 'move left'
alt-ctrl-shift-cmd-s = 'move down'
alt-ctrl-shift-cmd-w = 'move up'
alt-ctrl-shift-cmd-d = 'move right'

# alt-ctrl-shift-cmd-a = 'join-with left'
# alt-ctrl-shift-cmd-s = 'join-with down'
# alt-ctrl-shift-cmd-w = 'join-with up'
# alt-ctrl-shift-cmd-d = 'join-with right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-ctrl-shift-minus = 'resize smart -50'
alt-ctrl-shift-equal = 'resize smart +50'
alt-ctrl-shift-q = 'resize smart +50'
alt-ctrl-shift-e = 'resize smart -50'


# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
alt-ctrl-shift-1 = 'workspace 1'
alt-ctrl-shift-2 = 'workspace 2'
alt-ctrl-shift-3 = 'workspace 3'
alt-ctrl-shift-4 = 'workspace 4'
alt-ctrl-shift-5 = 'workspace 5'
alt-ctrl-shift-6 = 'workspace 6'
alt-ctrl-shift-7 = 'workspace 7'
alt-ctrl-shift-8 = 'workspace 8'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-ctrl-shift-cmd-1 = 'move-node-to-workspace 1'
alt-ctrl-shift-cmd-2 = 'move-node-to-workspace 2'
alt-ctrl-shift-cmd-3 = 'move-node-to-workspace 3'
alt-ctrl-shift-cmd-4 = 'move-node-to-workspace 4'
alt-ctrl-shift-cmd-5 = 'move-node-to-workspace 5'
alt-ctrl-shift-cmd-6 = 'move-node-to-workspace 6'
alt-ctrl-shift-cmd-7 = 'move-node-to-workspace 7'
alt-ctrl-shift-cmd-8 = 'move-node-to-workspace 8'

alt-ctrl-shift-enter = 'flatten-workspace-tree'
alt-ctrl-shift-space = 'move-workspace-to-monitor --wrap-around next'
alt-tab = 'workspace --wrap-around next'

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
# alt-shift-semicolon = 'mode service'
# alt-shift-enter = 'mode apps'

# alt-t = 'exec-and-forget open -a /Applications/Telegram.app'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
# esc = ['reload-config', 'mode main']
# r = ['flatten-workspace-tree', 'mode main'] # reset layout
# f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
# backspace = ['close-all-windows-but-current', 'mode main']

[mode.apps.binding]

[[on-window-detected]]
if.app-id = 'org.mozilla.firefox'
if.during-aerospace-startup = true
run = "move-node-to-workspace 2"

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = "move-node-to-workspace 2"

[[on-window-detected]]
if.app-id = 'com.todoist.mac.Todoist'
if.window-title-regex-substring = '^(?!.*\bTodoist\b).*'
run = "move-node-to-workspace 3"


[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
if.window-title-regex-substring = '^(?!.*\b~\b).*'
run= [
  "move-node-to-workspace 3"
]



[[on-window-detected]]
if.app-id = 'md.obsidian'
run = "move-node-to-workspace 3"

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = "move-node-to-workspace 1"

[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = "move-node-to-workspace 1"


[workspace-to-monitor-force-assignment]
1 = ['Built-in Retina Display']
2 = ['DELL U3421WE', 'Built-in Retina Display']
3 = ['V3L6W', 'Built-in Retina Display']
