# Start AeroSpace at login
start-at-login = false

after-startup-command = [
  'exec-and-forget borders active_color=0xff188bc2 inactive_color=0xff494d64 width=10.0'
]

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 80

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = []

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodness#disable-hide-app
automatically-unhide-macos-hidden-apps = true

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       5
outer.bottom =     5
outer.top =        5
outer.right =      5

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]

cmd-h = [] # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
alt-ctrl-comma = '''exec-and-forget osascript -e '
tell application "Firefox"
    open location "https://ballard.amazon.com/owa/#path=/calendar/view/WorkWeek"
end tell'
'''
alt-ctrl-period = '''exec-and-forget osascript -e '
tell application "Firefox"
    open location "https://ballard.amazon.com/owa/#path=/mail"
end tell'
'''
alt-ctrl-semicolon = '''exec-and-forget
CURRENT_WS_WINDOWS="$(aerospace list-windows --workspace focused)"
CURRENT_WS="$(aerospace list-workspaces --focused)"

# if window found in current space then focus
if echo "$CURRENT_WS_WINDOWS" | grep -q Firefox; then
  WINDOW_ID="$(echo "$CURRENT_WS_WINDOWS" | grep "Firefox" | cut -d "|" -f 1 | head -n 1)"
  aerospace focus --window-id "${WINDOW_ID//[[:blank:]]/}"

else
    open -a /Applications/Firefox.app --new
fi
'''

alt-ctrl-quote = '''exec-and-forget

#!/usr/bin/env bash

CURRENT_WS_WINDOWS="$(aerospace list-windows --workspace focused)"
CURRENT_WS="$(aerospace list-workspaces --focused)"

# if window found in current space then focus
if echo "$CURRENT_WS_WINDOWS" | grep -q Ghostty; then
  WINDOW_ID="$(echo "$CURRENT_WS_WINDOWS" | grep "Ghostty" | cut -d "|" -f 1 | head -n 1)"
  aerospace focus --window-id "${WINDOW_ID//[[:blank:]]/}"

# if window found in other workspace
else
  ALL_WINDOWS="$(aerospace list-windows --all)"
  if echo "$ALL_WINDOWS" | grep -q Ghostty; then
    WINDOW_ID="$(echo "$ALL_WINDOWS" | grep "Ghostty" | cut -d "|" -f 1 | head -n 1)"
    aerospace move-node-to-workspace --window-id "${WINDOW_ID//[[:blank:]]/}" "$CURRENT_WS" --focus-follows-window
  else
    open -a /Applications/Ghostty.app --background
    sleep 3
    ALL_WINDOWS="$(aerospace list-windows --all)"
    WINDOW_ID="$(echo "$ALL_WINDOWS" | grep "Ghostty" | cut -d "|" -f 1 | head -n 1)"
    aerospace move-node-to-workspace --window-id "${WINDOW_ID//[[:blank:]]/}" "$CURRENT_WS" --focus-follows-window
  fi
fi
'''

# https://github.com/ghostty-org/ghostty/discussions/3563
alt-ctrl-rightSquareBracket = '''exec-and-forget
#!/usr/bin/env bash

CURRENT_WS_WINDOWS="$(aerospace list-windows --workspace focused)"
CURRENT_WS="$(aerospace list-workspaces --focused)"

# if window found in current space then focus
if echo "$CURRENT_WS_WINDOWS" | grep -q Obsidian; then
  WINDOW_ID="$(echo "$CURRENT_WS_WINDOWS" | grep "Obsidian" | cut -d "|" -f 1 | head -n 1)"
  aerospace focus --window-id "${WINDOW_ID//[[:blank:]]/}"

# if window found in other workspace
else
  ALL_WINDOWS="$(aerospace list-windows --all)"
  if echo "$ALL_WINDOWS" | grep -q Obsidian; then
    WINDOW_ID="$(echo "$ALL_WINDOWS" | grep "Obsidian" | cut -d "|" -f 1 | head -n 1)"
    aerospace move-node-to-workspace --window-id "${WINDOW_ID//[[:blank:]]/}" "$CURRENT_WS" --focus-follows-window
  else
    open -a /Applications/Obsidian.app --background
    sleep 3
    ALL_WINDOWS="$(aerospace list-windows --all)"
    WINDOW_ID="$(echo "$ALL_WINDOWS" | grep "Obsidian" | cut -d "|" -f 1 | head -n 1)"
    aerospace move-node-to-workspace --window-id "${WINDOW_ID//[[:blank:]]/}" "$CURRENT_WS" --focus-follows-window
  fi
fi
'''

alt-ctrl-leftSquareBracket = '''exec-and-forget
#!/usr/bin/env bash

CURRENT_WS_WINDOWS="$(aerospace list-windows --workspace focused)"
CURRENT_WS="$(aerospace list-workspaces --focused)"

# if window found in current space then focus
if echo "$CURRENT_WS_WINDOWS" | grep -q Todoist; then
  WINDOW_ID="$(echo "$CURRENT_WS_WINDOWS" | grep "Todoist" | cut -d "|" -f 1 | head -n 1)"
  aerospace focus --window-id "${WINDOW_ID//[[:blank:]]/}"

# if window found in other workspace
else
  ALL_WINDOWS="$(aerospace list-windows --all)"
  if echo "$ALL_WINDOWS" | grep -q Todoist; then
    WINDOW_ID="$(echo "$ALL_WINDOWS" | grep "Todoist" | cut -d "|" -f 1 | head -n 1)"
    aerospace move-node-to-workspace --window-id "${WINDOW_ID//[[:blank:]]/}" "$CURRENT_WS" --focus-follows-window
  else
    open -a /Applications/Todoist.app --background
    sleep 3
    ALL_WINDOWS="$(aerospace list-windows --all)"
    WINDOW_ID="$(echo "$ALL_WINDOWS" | grep "Todoist" | cut -d "|" -f 1 | head -n 1)"
    aerospace move-node-to-workspace --window-id "${WINDOW_ID//[[:blank:]]/}" "$CURRENT_WS" --focus-follows-window
  fi
fi
'''
alt-ctrl-cmd-f = 'fullscreen'
alt-ctrl-f = 'layout h_accordion h_tiles'
alt-ctrl-b = 'balance-sizes'


# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-ctrl-a = 'focus left --boundaries workspace --boundaries-action wrap-around-the-workspace'
alt-ctrl-s = 'focus down --boundaries workspace --boundaries-action wrap-around-the-workspace'
alt-ctrl-w = 'focus up --boundaries workspace --boundaries-action wrap-around-the-workspace'
alt-ctrl-d = 'focus right --boundaries workspace --boundaries-action wrap-around-the-workspace'

alt-ctrl-h = 'focus left --boundaries workspace --boundaries-action wrap-around-the-workspace'
alt-ctrl-j = 'focus down --boundaries workspace --boundaries-action wrap-around-the-workspace'
alt-ctrl-k = 'focus up --boundaries workspace --boundaries-action wrap-around-the-workspace'
alt-ctrl-l = 'focus right --boundaries workspace --boundaries-action wrap-around-the-workspace'
# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-ctrl-cmd-a = 'move left'
alt-ctrl-cmd-s = 'move down'
alt-ctrl-cmd-w = 'move up'
alt-ctrl-cmd-d = 'move right'

alt-ctrl-cmd-h = 'move left'
alt-ctrl-cmd-j = 'move down'
alt-ctrl-cmd-k = 'move up'
alt-ctrl-cmd-l = 'move right'

shift-cmd-a = 'join-with left'
shift-cmd-s = 'join-with down'
shift-cmd-w = 'join-with up'
shift-cmd-d = 'join-with right'

shift-cmd-h = 'join-with left'
shift-cmd-j = 'join-with down'
shift-cmd-k = 'join-with up'
shift-cmd-l = 'join-with right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-ctrl-minus = 'resize smart -50'
alt-ctrl-equal = 'resize smart +50'
alt-ctrl-q = 'resize smart +50'
alt-ctrl-e = 'resize smart -50'


# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
alt-ctrl-1 = 'workspace 1-chat'
alt-ctrl-2 = 'workspace 2-dev'
alt-ctrl-3 = 'workspace 3-knowledge'
alt-ctrl-4 = 'workspace 4-casual'
alt-ctrl-5 = 'workspace 5'
alt-ctrl-6 = 'workspace 6'
alt-ctrl-7 = 'workspace 7'
alt-ctrl-8 = 'workspace 8'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-ctrl-cmd-1 = 'move-node-to-workspace 1-chat'
alt-ctrl-cmd-2 = 'move-node-to-workspace 2-dev'
alt-ctrl-cmd-3 = 'move-node-to-workspace 3-knowledge'
alt-ctrl-cmd-4 = 'move-node-to-workspace 4-casual'
alt-ctrl-cmd-5 = 'move-node-to-workspace 5'
alt-ctrl-cmd-6 = 'move-node-to-workspace 6'
alt-ctrl-cmd-7 = 'move-node-to-workspace 7'
alt-ctrl-cmd-8 = 'move-node-to-workspace 8'

alt-ctrl-enter = 'flatten-workspace-tree'
alt-ctrl-space = 'move-workspace-to-monitor --wrap-around next'
alt-tab = 'workspace --wrap-around next'

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
# alt-shift-semicolon = 'mode service'
# alt-shift-enter = 'mode apps'

# alt-t = 'exec-and-forget open -a /Applications/Telegram.app'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
# esc = ['reload-config', 'mode main']
# r = ['flatten-workspace-tree', 'mode main'] # reset layout
# f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
# backspace = ['close-all-windows-but-current', 'mode main']

[mode.apps.binding]

[[on-window-detected]]
if.app-id = 'org.mozilla.firefox'
if.during-aerospace-startup = true
run = "move-node-to-workspace 2-dev"

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
if.during-aerospace-startup = true
run = "move-node-to-workspace 2-dev"

[[on-window-detected]]
if.app-id = 'com.todoist.mac.Todoist'
if.during-aerospace-startup = true
if.window-title-regex-substring = '^(?!.*\bTodoist\b).*'
run = "move-node-to-workspace 3-knowledge"


[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
if.during-aerospace-startup = true
run= [
  "move-node-to-workspace 3-knowledge"
]


[[on-window-detected]]
if.app-id = 'com.omnigroup.OmniFocus4'
run = "move-node-to-workspace 3-knowledge"

[[on-window-detected]]
if.app-id = 'md.obsidian'
run = "move-node-to-workspace 3-knowledge"

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = "move-node-to-workspace 1-chat"

[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = "move-node-to-workspace 1-chat"

[[on-window-detected]]
if.app-id = 'com.amazon.Amazon-Chime'
run = "move-node-to-workspace 1-chat"


[workspace-to-monitor-force-assignment]
1-chat = ['Built-in Retina Display']
2-dev = ['LEN P32p-20', 'DELL U3421WE', 'Built-in Retina Display']
3-knowledge = ['LEN P32p-20', 'V3L6W', 'Built-in Retina Display']
