#!/bin/zsh

# VIEWERS
alias bat='bat --paging=never --color=always --style=numbers'
export MANPAGER='less -X';
export LESS_TERMCAP_md="${yellow}";

# Increase ZSH history size. Allow 32³ entries; the default is 500.
export HISTSIZE=32768
export SAVEHIST=HISTSIZE
# Omit duplicates and commands that begin with a space from history.
setopt hist_ignore_all_dups

# fix zsh tabbing expansion with fzf
setopt GLOB_COMPLETE

# Tools with settings
alias sudo='sudo '
alias grep='grep --color=auto'
alias ls="lsd"
alias csvlook="csvlook -l -I"

alias reload="exec ${SHELL} -l"
alias hg="history | grep"
alias pbc="pbcopy"
alias pbp="pbpaste"

alias pydebug="python3 -m pdb -c continue"
alias scalc="soffice --calc"
alias postgres-up="docker container run --name postgres-test-db -p 54320:5432 -e POSTGRES_USER=db -d postgres:9.6"

# FUNCTIONS
# alias twm="${HOME}/scripts/toggle-wm.sh"
alias awscred=${HOME}/scripts/update-aws-credentials.sh
