#!/bin/zsh

# VIEWERS
alias bat='bat --color=always --style=numbers'

# Tools with settings
alias sudo='sudo '
alias grep='grep --color=auto'
alias rg="rg --hidden -g '!*venv/*' -g '!*Box Sync*' -g '!*.git/*' -g '!*zsh_history' --no-messages"
alias ls="lsd"
alias csvlook="csvlook -l -I"
alias less='less -s -M -N -R -I -J'

alias reload="exec ${SHELL} -l"
alias hg="history | grep"
alias pbc="pbcopy"
alias pbp="pbpaste"

alias scalc="soffice --calc"

alias ssh=colorssh

alias notes="cd ~/Dropbox/notes/"
alias books="cd ~/Box\ Sync/books/"

alias vim=nvim
alias g=gemini
alias ag=antigravity