#!/bin/zsh

function twm {

    COMMAND=$1

    if [[ "$COMMAND" =~ ^(start|stop|restart)$ ]]; then
        brew services "${COMMAND}" chunkwm
        brew services "${COMMAND}" skhd
    else
        echo "${COMMAND} is not a valid option"
    fi

}

function awscred {

    USER=S1
    PASS=S2

    aws configure set aws_access_key_id $USER --profile cloud
    aws configure set aws_secret_access_key $PASS --profile cloud
}

function wttr()
{
    # change Paris to your default location
    local request="wttr.in/${1-Toronto}"
    [ "$(tput cols)" -lt 125 ] && request+='?n'
    curl -H "Accept-Language: ${LANG%_*}" --compressed "$request"
}
